export const tokenMock = {
    access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJFbWFpbCI6ImRpZWdvb3N2YWxkb3JlemVuZGVAY2xhZG0uY29tLmJyIiwidXNlclJvbGUiOiJhZG1pbiIsImlzcyI6IkN1bHR1cmUgQ29kZSBVc2VyIiwiYXVkIjoidXNlcnMgZnJvbSBDdWx0dXJlIENvZGUiLCJpYXQiOjE3MzE5Mzg4NjAsImV4cCI6MTczMTkzOTE2MH0.sZqOcJHuC11YtuEazlfia7W5sYfWqaIolXDzyoKcMeg"
}
